{
    "name": "Gelismis Faturalama ve Finans",
    "version": "19.0.1.0.0",
    "category": "Accounting/Accounting",
    "summary": "Odoo Community icin gelismis finans ve operasyonel muhasebe",
    "author": "Rasim Okutan",
    "license": "LGPL-3",
    "depends": ["account", "mail", "analytic"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/mail_template_data.xml",
        "data/cron_data.xml",
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "views/bank_reconciliation_views.xml",
        "views/budget_views.xml",
        "views/finance_followup_views.xml",
        "views/finance_dashboard_views.xml",
        "views/finance_report_views.xml",
        "views/menu_views.xml",
        "report/report_actions.xml",
        "report/partner_aging_report_templates.xml",
    ],
    "demo": ["demo/demo_data.xml"],
    "application": True,
    "installable": True,
}
